# Generated by Django 3.0.5 on 2021-09-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kvvk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Açıklama Başlığı', max_length=200, verbose_name='Name')),
                ('kvvk', models.FileField(upload_to='products/katalog/%y/%m/%d')),
            ],
        ),
    ]
