# Generated by Django 4.0.5 on 2022-09-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211107_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='noDropDown',
        ),
        migrations.RemoveField(
            model_name='product',
            name='normal_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_tr',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
