# Generated by Django 4.0.5 on 2022-09-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='Ürün Kodu Giriniz', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Ürün Kodu Giriniz', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='Ürün Kodu Giriniz', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_tr',
            field=models.CharField(default='Ürün Kodu Giriniz', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='Ürün Kodu Giriniz', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(default='Ürün Kodu Giriniz', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='Ürün Kodu Giriniz', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(default='Ürün Kodu Giriniz', max_length=200),
        ),
    ]
