# Generated by Django 4.0.5 on 2022-09-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_category_name_alter_category_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(default='Ürün Kodu Giriniz', max_length=200)),
                ('h2', models.CharField(default='Ürün Kodu Giriniz', max_length=200)),
                ('product', models.CharField(default='Ürün Kodu Giriniz', max_length=200)),
                ('image', models.CharField(default='Ürün Kodu Giriniz', max_length=200)),
            ],
        ),
    ]
