# Generated by Django 4.0.5 on 2022-09-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.BooleanField(default=False),
        ),
    ]
