# Generated by Django 3.0.5 on 2021-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210802_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=510, verbose_name='status:')),
                ('systemtime', models.CharField(max_length=510, verbose_name='systemtime:')),
                ('conversationİd', models.CharField(max_length=510, verbose_name='conversationİd:')),
                ('price', models.CharField(max_length=510, verbose_name='price:')),
                ('paidPrice', models.CharField(max_length=510, verbose_name='paidPrice:')),
                ('paymentid', models.CharField(max_length=510, verbose_name='paymentid:')),
                ('binNumber', models.CharField(max_length=510, verbose_name='binNumber:')),
                ('result_token', models.CharField(max_length=510, verbose_name='result_token:')),
                ('callBackURl', models.CharField(max_length=510, verbose_name='callBackURl:')),
                ('payment_token', models.CharField(max_length=510, verbose_name='payment_token:')),
            ],
        ),
    ]
