# Generated by Django 3.0.5 on 2021-09-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_returndata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returndata',
            name='callBackURl',
        ),
    ]
