# Generated by Django 3.0.5 on 2021-09-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_webhook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webhook',
            new_name='WebhookData',
        ),
    ]
