# Generated by Django 3.0.5 on 2021-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210906_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlast', models.CharField(max_length=510)),
                ('usertoken', models.CharField(max_length=510)),
            ],
        ),
    ]
