# Generated by Django 3.0.5 on 2021-09-13 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_usertokendata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokendata',
            name='userlast',
            field=models.ForeignKey(default='userlast', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
