# Generated by Django 3.0.5 on 2021-09-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210913_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokendata',
            name='userlast',
            field=models.CharField(max_length=510),
        ),
    ]
